openapi: 3.0.0
info:
  title: API Recipes
  description: API for test 3
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/SAMIRADA_1/API_Recipes/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
